name: Build

# Triggered on PRs against main branches
on:
  pull_request:
    branches:
      - master
      - hardcode-versions

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.6

    - name: Install Docusaurus dependencies
      run: bun install --no-save # do not generate a lockfile

    - name: Build Docusaurus and check for broken links
      run: bun run build
      env:
          BRANCH: ${{ github.base_ref }}
          BASE_URL: /docs/
